Repository jseidl/magic-areas, pull requests merged in 2024-09, with the labels that each got.

#380 Modernize and expand tests
  custom_components/magic_areas/__init__.py
  custom_components/magic_areas/base/presence.py
  scripts/test
  tests/__init__.py
  tests/common.py
  tests/conftest.py
  tests/const.py
  tests/mocks.py
  tests/test_aggregates.py
  tests/test_area_state.py
  tests/test_cover.py
  tests/test_init.py
  tests/test_primary_state.py
  tests/test_threshold.py
Labels: enhancement

#393 Fix unit of measurement resolution
  custom_components/magic_areas/sensor.py
Labels: hotfix

#397 Fixing threshold sensor test to pass on GitHub and minor version bumps + consolidation of latest releases
  hacs.json
  requirements-test.txt
  requirements.txt
  tests/test_threshold.py
Labels: chore

#400 Make schemas tolerant to extra keys
  custom_components/magic_areas/const.py
Labels: enhancement

#398 Keep-only presence sensors, for those pesky flappy sensors such as mmwave
  custom_components/magic_areas/base/magic.py
  custom_components/magic_areas/base/presence.py
  custom_components/magic_areas/config_flow.py
  custom_components/magic_areas/const.py
  custom_components/magic_areas/translations/de.json
  custom_components/magic_areas/translations/en.json
  custom_components/magic_areas/translations/es.json
  custom_components/magic_areas/translations/nl-NL.json
  custom_components/magic_areas/translations/pt-BR.json
  tests/conftest.py
  tests/test_area_state.py
Labels: feature

#404 Docs upgrade on README.md
  README.md
  assets/images/family-room-device.png
  assets/images/readme_combined_presence_sources.gif
  assets/images/temperature-aggregate.png
  assets/images/upstairs-controls.png
  config/configuration.yaml
Labels: documentation

#405 Release 4.1.0
  custom_components/magic_areas/manifest.json
  hacs.json
Labels: release

#410 feat(translation): add french translation file
  custom_components/magic_areas/translations/fr-FR.json
Labels: enhancement

#409 Update README.md
  README.md
Labels: documentation, enhancement

#415 Set control switches to CONFIG entity_category
  README.md
  custom_components/magic_areas/manifest.json
  custom_components/magic_areas/switch.py
  hacs.json
Labels: enhancement
