Repository jseidl/magic-areas, pull requests merged in 2024-02, with the labels that each got.

#300 Area Devices + Major code refactor
  custom_components/magic_areas/__init__.py
  custom_components/magic_areas/base.py
  custom_components/magic_areas/base/__init__.py
  custom_components/magic_areas/base/entities.py
  custom_components/magic_areas/base/magic.py
  custom_components/magic_areas/base/primitives.py
  custom_components/magic_areas/binary_sensor.py
  custom_components/magic_areas/climate.py
  custom_components/magic_areas/config_flow.py
  custom_components/magic_areas/const.py
  custom_components/magic_areas/cover.py
  custom_components/magic_areas/light.py
  custom_components/magic_areas/media_player.py
  custom_components/magic_areas/sensor.py
  custom_components/magic_areas/switch.py
  custom_components/magic_areas/util.py
  hacs.json
Labels: feature, enhancement

#301 Fixing condition to skip binary sensors w/o device class
  custom_components/magic_areas/binary_sensor.py
Labels: hotfix

#302 Checking if area was just occupied when bright before turning off
  custom_components/magic_areas/light.py
Labels: hotfix

#303 Adding support for binary sensors to act in ALL mode
  custom_components/magic_areas/base/entities.py
  custom_components/magic_areas/binary_sensor.py
  custom_components/magic_areas/const.py
Labels: enhancement

#305 Fix Meta-area Light Groups not showing up on area device
  custom_components/magic_areas/base/entities.py
  custom_components/magic_areas/light.py
Labels: hotfix

#306 Hotfix/climate group initialization
  custom_components/magic_areas/climate.py
Labels: hotfix

#307 Fixed CI pipeline now that ha-blueprint is deprecated
  .github/workflows/release.yaml
  .github/workflows/validation.yaml
Labels: hotfix

#310 Adding last_active_sensors to better help debug flipping sensors
  custom_components/magic_areas/base/entities.py
  custom_components/magic_areas/binary_sensor.py
  custom_components/magic_areas/const.py
Labels: enhancement

#311 Updating some metadata and readme for latest updates
  README.md
  hacs.json
Labels: chore

#314 Generalizing Meta area object creation so we can centralize fixes
  custom_components/magic_areas/__init__.py
  custom_components/magic_areas/config_flow.py
  custom_components/magic_areas/util.py
Labels: hotfix

#315 Add async to load_entities method in add_entities_when_ready
  custom_components/magic_areas/util.py
Labels: hotfix
